### ISSUE TITLE
ValueError: Wrong reference sequence for variant

### ISSUE THREAD

**Issue by ihodes** [hammerlab/vaxrank#127]
```
ValueError: Wrong reference sequence for variant Variant(contig='11', start=106262686, ref='GTGAAGG', alt='', reference_name='GRCm38') on transcript Transcript(transcript_id=ENSMUST00000021049, name=Psmc5-001, gene_id=ENSMUSG00000020708, gene_name=Psmc5, biotype=protein_coding, location=11:106256154-106263120)
```
@iskandr reports:

> Found it — the end of exon 9 is “GTGAAG” and the next intronic nt is “G”. So the variant deletes the end of the exon and the next nucleotide. Varcode only looks at the transcript sequence and apparently doesn’t clip the variant to only cover the exons

> This seems like it would likely cause a splice variant

> Since both the exonic and intronic splice signal is potentially damaged.

**Comment by iskandr** [comment]
Actual problem is with Varcode: https://github.com/hammerlab/varcode/issues/224
