### ISSUE TITLE
Remove all print statements (replace with logging)

### ISSUE THREAD

**Issue by ihodes** [hammerlab/vaxrank#14]

**Comment by iskandr** [comment]
@julia326 I think this is done, are there any lingering print statements?

**Comment by ihodes** [comment]
There appear not to be, just a lot of imports we don't need e.g. https://github.com/hammerlab/vaxrank/blob/3162da207489042573ca882cd0cf3b66058749bf/vaxrank/report.py#L15

**Comment by julia326** [comment]
from talking to Alex offline: those imports are necessary for python2 to act like python3, so leaving them in. No more prints in vaxrank, so I'll close this out but there are other logging issues (using separate loggers in different modules, etc.) which I'll file as issues in the different repos

**Comment by ihodes** [comment]
I was talking about the `print_function` in particular, which I don't think we're using? I don't have a strong opinion about removing it, though.
