### ISSUE TITLE
Add manufacturability to sliding window scores

### ISSUE THREAD

**Issue by iskandr** [hammerlab/vaxrank#2]
All else being equal we would like to (at least) minimize: 

1) longest hydrophobic stretch of amino acids
2) fraction of hydrophobic residues
3) longest stretch of histidine residues 
4) total number of cysteine residues (prevent disulfide bridges)
5) total number of methionine residues (prevent oxidation)
7) N-terminal cysteine, glutamine, or asparagine
8) C-terminal cysteine or proline
9) N-terminal glutamate or glutamine (prevent pyroglutamate formation) pairs 

I'm not sure about relative importance of these factors and I also don't know what else should be included. 

Sources for further information: 

* [Early Engineering Approaches to Improve Peptide Developability and Manufacturability]
(http://www.ncbi.nlm.nih.gov/pmc/articles/PMC4287292/)

* [Design Considerations for Peptide Synthesis](http://proteomics.rockefeller.edu/peptide_synthesis_information#design) 

* ["Peptide Design" from ThermoFisher](https://www.thermofisher.com/us/en/home/life-science/protein-biology/protein-biology-learning-center/protein-biology-resource-library/pierce-protein-methods/peptide-design.html)

@JPFinnigan What do you think?

**Comment by JPFinnigan** [comment]
Thus far hydrophobicity has been the biggest issue affecting recovery. In that regard C-terminal hydrophobicity has seemingly been more important than both N-terminal and total hydrophobicity. I spoke with the chemists at Peptide 2.0, and was told that synthesis proceeds in a C-to-N direction;  meaning that that the peptide is anchored to the solid-phase support by the residue at the C-terminus. After synthesis is complete the peptide needs to be cleaved from the support and the efficiency of this process is affected by the hydrophobicity the residues closest to the support. My understanding is that a very hydrophobic C-terminus leads to packing which inhibits cleavage which in-turn limits recovery.

A little while back I sent you a few plots in which I calculated the average hydrophobicity over all 5-7 mer window for the peptides we made for the B16-- including two that failed synthesis and needed to be modified. Even w/  the limited sample size seemed as though one could predict recovery by this simple method, by setting a C-terminal hydrophobicity threshold.  If you're interested I can forward the materials again..

I think that the other properties you listed are important, but given the overriding issue of solubility/hydrophobicity it may not be worth it to try to optimize for any of them aside from sliding window modifications to avoid specific single resides at C/N-termini (e.g  N-terminal glutamate).

**Comment by iskandr** [comment]
Suggestions from JPT:

1) [GRAVY score](https://www.researchgate.net/figure/230755139_fig3_Gravy-index-score-average-hydrophobicity-and-hydrophilicity-of-colon-proteins-measured)

2) Minimize number of adjacent hydrophobic residues

3) Minimize number of cysteines 

4) Avoid peptides with Asparagine Proline bonds 

5) Avoid N-terminal Gln, Glu, Asn, Cys

6) Avoid C-terminal Pro and Cys residues

**Comment by iskandr** [comment]
Started on a branch here: https://github.com/hammerlab/vaxrank/pull/55/

@JPFinnigan Would you only want to consider the hydrophobicity of the rightmost (C-terminal) 5-7 residues?
