### ISSUE TITLE
Generate HTML and PDF reports

### ISSUE THREAD

**Issue by iskandr** [hammerlab/vaxrank#3]
Currently only making a text file for vaccine peptides, would be nice to format this as HTML and then convert to PDF with [pdfkit](https://github.com/JazzCore/python-pdfkit)

**Comment by hammer** [comment]
@ihodes got some code for this w/ julia k?

**Comment by ihodes** [comment]
I do indeed; it needs to be modified to work directly with Vaxrank instead of through a database, but we've got a template to work with.
