### ISSUE TITLE
Variant in CSV output shouldn't Python string representation

### ISSUE THREAD

**Issue by iskandr** [hammerlab/vaxrank#49]
Currently the CSV output contains variants like this: "Variant(contig='16', start=4934325, ref='G', alt='A', reference_name='GRCh37')". 

We should instead use `variant.short_description`.

**Comment by iskandr** [comment]
@julia326 This is done, right?

**Comment by julia326** [comment]
Which CSV output? The result of `--output-csv` looks like this now, from the test data:

```
amino_acids,chr,pos,ref,alt,variant_rank,peptide_rank,mutation_start,mutation_end,combined_score,mutant_epitope_score,cterm_7mer_gravy_score,max_7mer_gravy_score,difficult_n_terminal_residue,c_terminal_cysteine,c_terminal_proline,cysteine_count,n_terminal_asparagine,asparagine_proline_bond_count
DNTVIHAVNNMTLKVWNSYTGQL,9,82927102,G,T,1,1,5,6,3.6919,0.8954,-0.9143,1.0429,0,0,0,0,0,0
```

Do you mean the ASCII report or something else?

**Comment by iskandr** [comment]
I think there was a version where variants were a Python string
representation, but this is good.
