### ISSUE TITLE
Add COSMIC ID if present

### ISSUE THREAD

**Issue by julia326** [hammerlab/vaxrank#76]
Check variants against COSMIC, and include a link in the HTML/PDF report if present

**Comment by ihodes** [comment]
I'm not sure we need this; what's the benefit of adding the COSMIC ID?

**Comment by julia326** [comment]
from conversation with @timodonnell, sounded like it would be a useful thing to have in the clinician report - Tim, could you elaborate?

**Comment by hammer** [comment]
Well it would be useful to know if a neoantigen comes from a driver or a passenger gene. Getting that information from COSMIC and into our reports would be great.

**Comment by ihodes** [comment]
From @timodonnell a nice suggestion for implementation
> maybe just add a Databases row for each variant that has links like [COSMIC] [WUSTL] [CORNELL] etc ?
