### ISSUE TITLE
Add option to drop variants with only N total alt reads supporting *just* the variant locus

### ISSUE THREAD

**Issue by ihodes** [hammerlab/vaxrank#87]
E.g. our current IND says we need 3 supporting the variant to use them. 

The current min-reads-supporting-variant-sequence is a stronger filter; instead of just at the variant locus, this is across the entire variant sequence.

**Comment by iskandr** [comment]
A slightly more general version of this is implemented by the existing `--min-variant-sequence-coverage` option, which clips variant sequences to only the regions supported by N reads (and if there are fewer than N supporting reads then the variant gets skipped)
