### ISSUE TITLE
Why didn't we find this variant supported?

### ISSUE THREAD

**Issue by ihodes** [hammerlab/vaxrank#97]
![screen shot 2016-12-08 at 12 11 05 pm](https://cloud.githubusercontent.com/assets/167803/21019688/68b7c58a-bd3f-11e6-87c3-6e139c21f05c.png)

This variant didn't make it into the report for some reason (this is RNA support being shown), all well-aligned good data.

**Comment by ihodes** [comment]
Also one like this 
![screen shot 2016-12-08 at 12 53 57 pm](https://cloud.githubusercontent.com/assets/167803/21021176/6a7187c0-bd45-11e6-99ff-16534672c1ce.png)

**Comment by iskandr** [comment]
These are all by exon boundaries (I think -- can't see the annotation track in these screen shots). After dropping all the multi-exon spliced reads we're left with a bunch of reads that contain intronic sequences (blame RiboZero). Since the intronic sequences disagree with all annotated transcripts then we never end up discovering a reading frame for these variants.

**Comment by ihodes** [comment]
Would it be reasonable and feasible to stop reading cDNA at exon boundaries, so when we inevitably get intronic RNA in some reads, they aren't effectively thrown out?

**Comment by iskandr** [comment]
We can certainly rely on the reference more, particularly if we give up
trying to detect altered splicing.

**Comment by ihodes** [comment]
Ah interesting, where/how are we trying to detect altered splicing?

**Comment by ihodes** [comment]
@julia326 @iskandr can we close this/have we solved this?

**Comment by julia326** [comment]
I don't think we detect altered splicing (@iskandr please chime in if I'm wrong about this) - and the recent change to count intronic reads as reference mismatches after the exon boundary will actually make us throw out more reads. Coupled with these Ribozero side effects, that could be problematic. Is this a variant we would've wanted to keep, or should we double down on working with poly-A capture in the future?

**Comment by iskandr** [comment]
@julia326 Define "detect" :-) -- we were certainly detecting it in this case, just incorrectly.

**Comment by iskandr** [comment]
@ihodes How do these variants look after our changes to indel realignment?

**Comment by iskandr** [comment]
@ihodes @julia326 When samples are degraded and/or prepared with ribosomal depletion we should count mismatches on both sides of the variant, which will penalize variant sequences that look like abnormal splicing.

**Comment by iskandr** [comment]
Closing, since this is really an isovar issue: https://github.com/hammerlab/isovar/issues/55 (which will be fixed by https://github.com/hammerlab/isovar/pull/80)
